### ISSUE TITLE
'g_simpleProp' not found

### ISSUE THREAD

**Issue by amosbird** [vovkos/jancy#1]
Hi, I'm trying to embed jancy into a c++ project. I did a quick test 
```
 ❯ jancy/bin/Release/jnc_sample_02_embed_cpp /usr/local/share/jancy_b/samples/jnc/00_HelloWorld.jnc
```
but it failed :  'g_simpleProp' not found

What did I miss? Thanks!

**Comment by vovkos** [comment]
Both ``jnc_sample_01_embed_c`` and ``jnc_sample_02_embed_cpp`` show how to establish two-way interaction between a host app (C/C++) and embedded script in Jancy language. To let Jancy call into the host app, these sample attempt to map C/C++ implementation of functions and properties defined in the ``script.jnc`` file (which lies in their corresponding source folders, e.g., ``<jancy_root>/samples/jnc_sample_02_embed_cpp/script.jnc``. One of those properties to map is ``g_simpleProp`` -- it's not defined in ``HelloWorld.jnc``, hence, the error.

Therefore, these two samples should be started like this:
```
<build_dir>/jancy/bin/release/jnc_sample_02_embed_cpp <jancy_root>/samples/jnc_sample_02_embed_cpp/script.jnc
```
To start other samples from the ``<jancy_root>/samples/jnc`` folder (those samples do not define any external functions to be mapped by a host application), simply run:
```
<build_dir>/jancy/bin/release/jancy <jancy_root>/samples/jnc/00_HelloWorld.jnc
```

Hope that helps

**Comment by amosbird** [comment]
Thanks!
