### ISSUE TITLE
using namespace introduces protected namespace member into global namespace

### ISSUE THREAD

**Issue by ghost** [vovkos/jancy#7]
This may be a bug. It messes up the global namespace... I had got to prefixing such members to escape redefinition.
Also, any plan to support file scope-private? (i.e. the 'static' specifier as in C/C++. Currently static global variable doesn't seem to be different.)
Any way, hoping for some features to exclude some variables & named types from the source file which is including(or importing) them.

**Comment by vovkos** [comment]
> This may be a bug. It messes up the global namespace... I had got to prefixing such members to escape redefinition.

Could you clarify, please? Also, a snippet to reproduce the issue?

> Currently static global variable doesn't seem to be different

Yes, currently, `static` doesn't change the linkage/visibility of a global variable; this needs to be changed to work the same as in C/C++

**Comment by ghost** [comment]
namespace A {
    protected int Var = 100;
}
using namespace A;
void main() {
    printf("%d\n", Var); // no error.
}
If I remove "using namespace A;":
`C:\Users\I\jancy\bin\test.jnc(6,20): undeclared identifier 'Var'`
If I change "Var" to "A.Var":
`C:\Users\I\jancy\bin\test.jnc(6,22): 'A.Var' is protected`

**Comment by vovkos** [comment]
Yes, `public`/`protected` access levels are currently only checked inside the member operator; must be extended for cases when  identifier lookups end up traversing the `using` sets. Should be an easy fix; I'll leave a comment here as soon as it's done.

**Comment by vovkos** [comment]
The reported issue of "being able to access `protected` members of a namespace via the `using` directive" is fixed. Please take a look and re-open the issue if you find a problem.
